language: ruby
rvm:
- 2.3.1
deploy:
  provider: heroku
  api_key:
    secure: Y2yFgQd4MzIxmdst5hGhmZDAZ8G+1L6YTvHrFOPKf1QSDncfQmD9m9Mncz3QvONJE9pOFFD/rk1C2BBfYtsCWURumRIQ/vsrXhYzVPMEHaD0tAGp3kdx6XQz0LRIAEwPn6krgnQUmd1TMo0YaACRB8k1/DCDAgDmvfvRH2inSKiT2SG9hFXgyPzjkhtS+qll5ZWwKcLdlqXb+Qt3NIQvFJB1jJYZ+pUhgD6qhvxFL4EyBTGxEOGBNAXV8pONMI2eFO38P5t499N+wigFvylhmirvl6mY0dBSbXYCap0CWS+8hcOzFIJWGHY4k+6ZqsKJ8ekhdUklWI92J2MTueNefzjTkbtHFaZVArxYK+G2BKPZ0RDZ6maNY/hxinhfNw24ri16TOPP127Avq5ASEQz3Tuqi23uO+mvlnk8UsmMxuEcwmp7M5mNL+OQgGAOqlSCfZjZWh1EUiGwgSYk3v2gyJ3RM8JMSDpnPOFDSyaGkv4OFfr67nYJS9czdJnvUMkZ5uy/8jSmDw99Nrmzb0jzVEzHbfRFKTpzXVD7XmNtLKgsNK3BeYBGX+PpowqmJha0GA5iu7xTqiFB6lPkeohheDlxBLGBQ0W+T0If3ZQDsJdxwLAhDXDJrFTYuoa0ZjSi9fcwldVGZd45iRt0MYgG5ox7HunXt374V1pf1CF8mdg=
  app: lpa2
  on:
    repo: LPA2-Automne2016/projet
